command:
  - "uvicorn"
  - "app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: FRAUD_CATALOG
    value: "elexon_app_for_settlement_acc_catalog"
  - name: FRAUD_GOLD_SCHEMA
    value: "investec_fraud_aml_gold"
  - name: FRAUD_SILVER_SCHEMA
    value: "investec_fraud_aml_silver"
  - name: FRAUD_WAREHOUSE_ID
    value: "d0305022e6c3db8e"
  - name: SENTINEL_GENIE_SPACE
    value: "01f183691e8f14f18ae80b78b6ffae8b"
  - name: SENTINEL_DASHBOARD_ID
    value: "01f1843c859f1acb97f76971d642826c"
  - name: DATABRICKS_HOST
    value: "https://fevm-elexon-app-for-settlement-acc.cloud.databricks.com"
